version: "3"

# TODO move sensitive data to variables (usernames, passwords, etc.)
services:
  grafana:
    hostname: grafana
    image: grafana/grafana:7.3.1
    networks:
      internal:
      external:
    expose:
      - 3000
    ports:
      - 3000:3000
  timescaledb:
    hostname: postgres
    image: timescale/timescaledb:1.7.4-pg12
    networks:
      internal:
        aliases:
          - postgres
      external:
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_DB: home_monitor
    expose:
      - 5432
    ports:
      - 5432:5432
  home-monitor-server:
    build: .
    networks:
      internal:
      external:
    expose:
      - 8080
    ports:
      - 8080:8080
    environment:
      DB_JDBC_URL: "jdbc:postgresql://postgres:5432/home_monitor"
      DB_USERNAME: postgres
      DB_PASSWORD: password
networks:
  external:
  internal:
